"""Add Topic and TopicPassage

Revision ID: 70678a229903
Revises: d27d68fbf98c
Create Date: 2026-06-23 00:48:32.486456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.settings import get_settings


# revision identifiers, used by Alembic.
revision: str = "70678a229903"
down_revision: Union[str, Sequence[str], None] = "d27d68fbf98c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    schema = get_settings().DB_SCHEMA
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_topics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_user_defined", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    op.create_index(
        "kb_topics_project_idx",
        "kb_topics",
        ["tenant_id", "project_id", "is_user_defined"],
        unique=False,
        schema=schema,
    )
    op.create_table(
        "kb_topic_passages",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("passage_id", sa.UUID(), nullable=False),
        sa.Column("relevance_score", sa.Float(), server_default="1.0", nullable=False),
        sa.ForeignKeyConstraint(["passage_id"], [f"{schema}.kb_passages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], [f"{schema}.kb_topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topic_id", "passage_id"),
        schema=schema,
    )
    op.create_index("kb_topic_passages_reverse_idx", "kb_topic_passages", ["passage_id"], unique=False, schema=schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    schema = get_settings().DB_SCHEMA
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP INDEX IF EXISTS {schema}.kb_topic_passages_reverse_idx")
    op.execute(f"DROP TABLE IF EXISTS {schema}.kb_topic_passages")
    op.execute(f"DROP INDEX IF EXISTS {schema}.kb_topics_project_idx")
    op.execute(f"DROP TABLE IF EXISTS {schema}.kb_topics")
    # ### end Alembic commands ###
