"""Add embedding to kb_topics

Revision ID: afc4c39caf08
Revises: f8bf0a244010
Create Date: 2026-06-24 02:59:28.593826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'afc4c39caf08'
down_revision: Union[str, Sequence[str], None] = 'f8bf0a244010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_topics', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True), schema='evidence_kb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_topics', 'embedding', schema='evidence_kb')
    # ### end Alembic commands ###
