"""initial_schema

Revision ID: d27d68fbf98c
Revises: 
Create Date: 2026-06-21 15:45:21.485476

"""
import os
from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd27d68fbf98c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_retrieval_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), server_default='hybrid', nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('debug', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=os.environ.get('DB_SCHEMA', 'evidence_kb')
    )
    op.create_index('kb_retrieval_runs_project_idx', 'kb_retrieval_runs', ['tenant_id', 'project_id', 'created_at'], unique=False, schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.create_table('kb_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('external_source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('file_ref', sa.Text(), nullable=True),
    sa.Column('checksum', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Text(), server_default='candidate', nullable=False),
    sa.Column('retrieval_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('quality_warnings', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('text', 'markdown', 'html', 'pdf', 'web')", name='kb_sources_source_type_check'),
    sa.CheckConstraint("status IN ('candidate', 'certified', 'deprecated', 'rejected')", name='kb_sources_status_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'external_source_id', name='kb_sources_external_unique'),
    schema=os.environ.get('DB_SCHEMA', 'evidence_kb')
    )
    op.create_index('kb_sources_project_idx', 'kb_sources', ['tenant_id', 'project_id', 'created_at'], unique=False, schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.create_index('kb_sources_status_idx', 'kb_sources', ['status', 'retrieval_enabled'], unique=False, schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.create_table('kb_ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default='processing', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'processing', 'completed', 'failed')", name='kb_ingestion_runs_status_check'),
    sa.ForeignKeyConstraint(['source_id'], [f"{os.environ.get('DB_SCHEMA', 'evidence_kb')}.kb_sources.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=os.environ.get('DB_SCHEMA', 'evidence_kb')
    )
    op.create_index('kb_ingestion_runs_source_idx', 'kb_ingestion_runs', ['source_id', 'created_at'], unique=False, schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    from app.settings import get_settings
    dim = get_settings().EMBEDDING_DIMENSIONS

    op.create_table('kb_passages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default='text', nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), server_default='1', nullable=False),
    sa.Column('quality_warnings', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Text(), server_default='candidate', nullable=False),
    sa.Column('retrieval_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=dim), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', text)", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('candidate', 'certified', 'deprecated', 'rejected')", name='kb_passages_status_check'),
    sa.ForeignKeyConstraint(['source_id'], [f"{os.environ.get('DB_SCHEMA', 'evidence_kb')}.kb_sources.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'block_id', name='kb_passages_source_block_unique'),
    schema=os.environ.get('DB_SCHEMA', 'evidence_kb')
    )
    op.create_index('kb_passages_embedding_idx', 'kb_passages', ['embedding'], unique=False, schema=os.environ.get('DB_SCHEMA', 'evidence_kb'), postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('kb_passages_project_export_idx', 'kb_passages', ['tenant_id', 'project_id', 'source_id', 'order'], unique=False, schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.create_index('kb_passages_project_filter_idx', 'kb_passages', ['tenant_id', 'project_id', 'status', 'retrieval_enabled'], unique=False, schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.create_index('kb_passages_project_quality_idx', 'kb_passages', ['tenant_id', 'project_id', 'quality_score'], unique=False, schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.create_index('kb_passages_search_idx', 'kb_passages', ['search_vector'], unique=False, schema=os.environ.get('DB_SCHEMA', 'evidence_kb'), postgresql_using='gin')
    op.create_index('kb_passages_source_idx', 'kb_passages', ['source_id', 'order'], unique=False, schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.create_table('kb_retrieved_passages',
    sa.Column('retrieval_run_id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('bm25_rank', sa.Integer(), nullable=True),
    sa.Column('vector_rank', sa.Integer(), nullable=True),
    sa.Column('rrf_score', sa.Float(), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('used_in_answer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], [f"{os.environ.get('DB_SCHEMA', 'evidence_kb')}.kb_passages.id"], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieval_run_id'], [f"{os.environ.get('DB_SCHEMA', 'evidence_kb')}.kb_retrieval_runs.id"], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('retrieval_run_id', 'passage_id'),
    schema=os.environ.get('DB_SCHEMA', 'evidence_kb')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kb_retrieved_passages', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_index('kb_passages_source_idx', table_name='kb_passages', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_index('kb_passages_search_idx', table_name='kb_passages', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'), postgresql_using='gin')
    op.drop_index('kb_passages_project_quality_idx', table_name='kb_passages', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_index('kb_passages_project_filter_idx', table_name='kb_passages', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_index('kb_passages_project_export_idx', table_name='kb_passages', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_index('kb_passages_embedding_idx', table_name='kb_passages', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'), postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('kb_passages', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_index('kb_ingestion_runs_source_idx', table_name='kb_ingestion_runs', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_table('kb_ingestion_runs', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_index('kb_sources_status_idx', table_name='kb_sources', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_index('kb_sources_project_idx', table_name='kb_sources', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_table('kb_sources', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_index('kb_retrieval_runs_project_idx', table_name='kb_retrieval_runs', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    op.drop_table('kb_retrieval_runs', schema=os.environ.get('DB_SCHEMA', 'evidence_kb'))
    # ### end Alembic commands ###
