"""Add communities and retrieval traces

Revision ID: 1a49fe919cf6
Revises: c5cb3f160a44
Create Date: 2026-06-14 03:35:06.409494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a49fe919cf6'
down_revision: Union[str, Sequence[str], None] = 'c5cb3f160a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_community_id', sa.UUID(), nullable=True),
    sa.Column('algorithm', sa.String(length=255), nullable=False),
    sa.Column('algorithm_version', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_community_id'], ['lgs.communities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='lgs'
    )
    op.create_table('retrieval_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), server_default='', nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('expanded_query', sa.Text(), nullable=True),
    sa.Column('budget_preset', sa.String(length=50), nullable=False),
    sa.Column('relevance_test_budget', sa.Integer(), nullable=False),
    sa.Column('subquery_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lgs'
    )
    op.create_table('retrieval_trace_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['lgs.retrieval_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='lgs'
    )
    op.create_table('term_community_memberships',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('membership_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['lgs.communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['lgs.terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_id', 'term_id'),
    schema='lgs'
    )
    op.alter_column('documents', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='lgs')
    op.alter_column('terms', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='lgs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('terms', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='lgs')
    op.alter_column('documents', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='lgs')
    op.drop_table('term_community_memberships', schema='lgs')
    op.drop_table('retrieval_trace_steps', schema='lgs')
    op.drop_table('retrieval_traces', schema='lgs')
    op.drop_table('communities', schema='lgs')
    # ### end Alembic commands ###
