"""Initial lgs schema

Revision ID: c5cb3f160a44
Revises: 
Create Date: 2026-06-12 19:45:48.608703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'c5cb3f160a44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE SCHEMA IF NOT EXISTS lgs;')
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), server_default='', nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('document_name', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('normalized_content', sa.Text(), nullable=False),
    sa.Column('content_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lgs'
    )
    op.create_index('documents_collection_idx', 'documents', ['collection_id'], unique=False, schema='lgs')
    op.create_index('documents_source_idx', 'documents', ['source_id'], unique=False, schema='lgs')
    op.create_table('graph_refinement_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('proposal_type', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), server_default='pending', nullable=False),
    sa.Column('created_by_agent', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='lgs'
    )
    op.create_table('terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('raw', 'verified', 'merged', 'flagged', name='term_status', schema='lgs'), server_default='raw', nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['lgs.terms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'collection_id', 'normalized_text', 'label', name='terms_unique'),
    schema='lgs'
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=False),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', content)", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['lgs.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='lgs'
    )
    op.create_index('chunks_document_idx', 'chunks', ['document_id'], unique=False, schema='lgs')
    op.create_index('chunks_embedding_idx', 'chunks', ['embedding'], unique=False, schema='lgs', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'halfvec_cosine_ops'})
    op.create_index('chunks_search_idx', 'chunks', ['search_vector'], unique=False, schema='lgs', postgresql_using='gin')
    op.create_table('graph_mutation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('mutation_type', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['lgs.graph_refinement_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='lgs'
    )
    op.create_table('term_cooccurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('term_a_id', sa.UUID(), nullable=False),
    sa.Column('term_b_id', sa.UUID(), nullable=False),
    sa.Column('cooccurrence_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('weight', sa.Float(), server_default='1.0', nullable=False),
    sa.ForeignKeyConstraint(['term_a_id'], ['lgs.terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_b_id'], ['lgs.terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'term_a_id', 'term_b_id', name='term_cooccurrences_collection_id_term_a_id_term_b_id_unique'),
    schema='lgs'
    )
    op.create_table('chunk_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('refined_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['lgs.chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['lgs.terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'term_id', 'start_offset', 'end_offset', 'label', name='chunk_terms_span_unique'),
    schema='lgs'
    )
    op.create_index('chunk_terms_chunk_idx', 'chunk_terms', ['chunk_id'], unique=False, schema='lgs')
    op.create_index('chunk_terms_term_idx', 'chunk_terms', ['term_id'], unique=False, schema='lgs')
    op.create_table('term_cooccurrence_chunks',
    sa.Column('cooccurrence_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['lgs.chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cooccurrence_id'], ['lgs.term_cooccurrences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cooccurrence_id', 'chunk_id'),
    schema='lgs'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term_cooccurrence_chunks', schema='lgs')
    op.drop_index('chunk_terms_term_idx', table_name='chunk_terms', schema='lgs')
    op.drop_index('chunk_terms_chunk_idx', table_name='chunk_terms', schema='lgs')
    op.drop_table('chunk_terms', schema='lgs')
    op.drop_table('term_cooccurrences', schema='lgs')
    op.drop_table('graph_mutation_events', schema='lgs')
    op.drop_index('chunks_search_idx', table_name='chunks', schema='lgs', postgresql_using='gin')
    op.drop_index('chunks_embedding_idx', table_name='chunks', schema='lgs', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'halfvec_cosine_ops'})
    op.drop_index('chunks_document_idx', table_name='chunks', schema='lgs')
    op.drop_table('chunks', schema='lgs')
    op.drop_table('terms', schema='lgs')
    op.drop_table('graph_refinement_proposals', schema='lgs')
    op.drop_index('documents_source_idx', table_name='documents', schema='lgs')
    op.drop_index('documents_collection_idx', table_name='documents', schema='lgs')
    op.drop_table('documents', schema='lgs')
    op.execute('DROP SCHEMA IF EXISTS lgs;')
    # ### end Alembic commands ###
