// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { BulkCurationData, BulkCurationErrors, BulkCurationResponses, DeleteProjectData, DeleteProjectErrors, DeleteProjectResponses, DeleteSourceData, DeleteSourceErrors, DeleteSourceResponses, DeleteSourceWithProjectData, DeleteSourceWithProjectErrors, DeleteSourceWithProjectResponses, ExportPassagesData, ExportPassagesErrors, ExportPassagesResponses, FindStaleSourcesData, FindStaleSourcesErrors, FindStaleSourcesResponses, FindWeakPassagesData, FindWeakPassagesErrors, FindWeakPassagesResponses, GetConceptGraphData, GetConceptGraphErrors, GetConceptGraphResponses, GetIngestionRunData, GetIngestionRunErrors, GetIngestionRunResponses, GetSourceData, GetSourceDownloadUrlData, GetSourceDownloadUrlErrors, GetSourceDownloadUrlResponses, GetSourceErrors, GetSourceResponses, GetSourceViewerUrlData, GetSourceViewerUrlErrors, GetSourceViewerUrlResponses, GetSourceWithProjectData, GetSourceWithProjectErrors, GetSourceWithProjectResponses, GetSurroundingPassagesData, GetSurroundingPassagesErrors, GetSurroundingPassagesResponses, HealthCheckData, HealthCheckResponses, IngestPdfData, IngestPdfErrors, IngestPdfResponses, IngestSourceData, IngestSourceErrors, IngestSourceResponses, InspectPassageData, InspectPassageErrors, InspectPassageResponses, ListPassagesData, ListPassagesErrors, ListPassagesResponses, ListRunsForProjectData, ListRunsForProjectErrors, ListRunsForProjectResponses, ListSourcesData, ListSourcesErrors, ListSourcesResponses, ListTopicsData, ListTopicsErrors, ListTopicsResponses, MetadataData, MetadataResponses, RetrieveData, RetrieveErrors, RetrieveResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health Check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>): RequestResult<HealthCheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Metadata
 */
export const metadata = <ThrowOnError extends boolean = false>(options?: Options<MetadataData, ThrowOnError>): RequestResult<MetadataResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MetadataResponses, unknown, ThrowOnError>({ url: '/metadata', ...options });

/**
 * Ingest Source
 */
export const ingestSource = <ThrowOnError extends boolean = false>(options: Options<IngestSourceData, ThrowOnError>): RequestResult<IngestSourceResponses, IngestSourceErrors, ThrowOnError> => (options.client ?? client).post<IngestSourceResponses, IngestSourceErrors, ThrowOnError>({
    url: '/v1/ingest/source',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ingest Pdf
 */
export const ingestPdf = <ThrowOnError extends boolean = false>(options: Options<IngestPdfData, ThrowOnError>): RequestResult<IngestPdfResponses, IngestPdfErrors, ThrowOnError> => (options.client ?? client).post<IngestPdfResponses, IngestPdfErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/v1/ingest/pdf',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get Ingestion Run
 */
export const getIngestionRun = <ThrowOnError extends boolean = false>(options: Options<GetIngestionRunData, ThrowOnError>): RequestResult<GetIngestionRunResponses, GetIngestionRunErrors, ThrowOnError> => (options.client ?? client).get<GetIngestionRunResponses, GetIngestionRunErrors, ThrowOnError>({ url: '/v1/ingest/runs/{run_id}', ...options });

/**
 * List Runs For Project
 */
export const listRunsForProject = <ThrowOnError extends boolean = false>(options: Options<ListRunsForProjectData, ThrowOnError>): RequestResult<ListRunsForProjectResponses, ListRunsForProjectErrors, ThrowOnError> => (options.client ?? client).get<ListRunsForProjectResponses, ListRunsForProjectErrors, ThrowOnError>({ url: '/v1/ingest/projects/{project_id}/runs', ...options });

/**
 * Find Stale Sources
 *
 * Return sources that need attention: not certified, disabled retrieval, or have warnings.
 */
export const findStaleSources = <ThrowOnError extends boolean = false>(options: Options<FindStaleSourcesData, ThrowOnError>): RequestResult<FindStaleSourcesResponses, FindStaleSourcesErrors, ThrowOnError> => (options.client ?? client).get<FindStaleSourcesResponses, FindStaleSourcesErrors, ThrowOnError>({ url: '/v1/projects/{project_id}/sources/stale', ...options });

/**
 * List Sources
 */
export const listSources = <ThrowOnError extends boolean = false>(options: Options<ListSourcesData, ThrowOnError>): RequestResult<ListSourcesResponses, ListSourcesErrors, ThrowOnError> => (options.client ?? client).get<ListSourcesResponses, ListSourcesErrors, ThrowOnError>({ url: '/v1/projects/{project_id}/sources', ...options });

/**
 * Delete Source With Project
 */
export const deleteSourceWithProject = <ThrowOnError extends boolean = false>(options: Options<DeleteSourceWithProjectData, ThrowOnError>): RequestResult<DeleteSourceWithProjectResponses, DeleteSourceWithProjectErrors, ThrowOnError> => (options.client ?? client).delete<DeleteSourceWithProjectResponses, DeleteSourceWithProjectErrors, ThrowOnError>({ url: '/v1/projects/{project_id}/sources/{external_source_id}', ...options });

/**
 * Get Source With Project
 */
export const getSourceWithProject = <ThrowOnError extends boolean = false>(options: Options<GetSourceWithProjectData, ThrowOnError>): RequestResult<GetSourceWithProjectResponses, GetSourceWithProjectErrors, ThrowOnError> => (options.client ?? client).get<GetSourceWithProjectResponses, GetSourceWithProjectErrors, ThrowOnError>({ url: '/v1/projects/{project_id}/sources/{external_source_id}', ...options });

/**
 * Delete Project
 */
export const deleteProject = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectData, ThrowOnError>): RequestResult<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError> => (options.client ?? client).delete<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError>({ url: '/v1/projects/{project_id}', ...options });

/**
 * Delete Source
 */
export const deleteSource = <ThrowOnError extends boolean = false>(options: Options<DeleteSourceData, ThrowOnError>): RequestResult<DeleteSourceResponses, DeleteSourceErrors, ThrowOnError> => (options.client ?? client).delete<DeleteSourceResponses, DeleteSourceErrors, ThrowOnError>({ url: '/v1/sources/{external_source_id}', ...options });

/**
 * Get Source
 */
export const getSource = <ThrowOnError extends boolean = false>(options: Options<GetSourceData, ThrowOnError>): RequestResult<GetSourceResponses, GetSourceErrors, ThrowOnError> => (options.client ?? client).get<GetSourceResponses, GetSourceErrors, ThrowOnError>({ url: '/v1/sources/{external_source_id}', ...options });

/**
 * Get Source Download Url
 */
export const getSourceDownloadUrl = <ThrowOnError extends boolean = false>(options: Options<GetSourceDownloadUrlData, ThrowOnError>): RequestResult<GetSourceDownloadUrlResponses, GetSourceDownloadUrlErrors, ThrowOnError> => (options.client ?? client).get<GetSourceDownloadUrlResponses, GetSourceDownloadUrlErrors, ThrowOnError>({ url: '/v1/sources/{external_source_id}/download-url', ...options });

/**
 * Get Source Viewer Url
 */
export const getSourceViewerUrl = <ThrowOnError extends boolean = false>(options: Options<GetSourceViewerUrlData, ThrowOnError>): RequestResult<GetSourceViewerUrlResponses, GetSourceViewerUrlErrors, ThrowOnError> => (options.client ?? client).get<GetSourceViewerUrlResponses, GetSourceViewerUrlErrors, ThrowOnError>({ url: '/v1/sources/{external_source_id}/viewer-url', ...options });

/**
 * Find Weak Passages
 *
 * Return passages that need attention: low quality, warnings, disabled retrieval, or rejected.
 */
export const findWeakPassages = <ThrowOnError extends boolean = false>(options: Options<FindWeakPassagesData, ThrowOnError>): RequestResult<FindWeakPassagesResponses, FindWeakPassagesErrors, ThrowOnError> => (options.client ?? client).get<FindWeakPassagesResponses, FindWeakPassagesErrors, ThrowOnError>({ url: '/v1/passages/weak', ...options });

/**
 * List Passages
 */
export const listPassages = <ThrowOnError extends boolean = false>(options: Options<ListPassagesData, ThrowOnError>): RequestResult<ListPassagesResponses, ListPassagesErrors, ThrowOnError> => (options.client ?? client).get<ListPassagesResponses, ListPassagesErrors, ThrowOnError>({ url: '/v1/sources/{source_id}/passages', ...options });

/**
 * Inspect Passage
 */
export const inspectPassage = <ThrowOnError extends boolean = false>(options: Options<InspectPassageData, ThrowOnError>): RequestResult<InspectPassageResponses, InspectPassageErrors, ThrowOnError> => (options.client ?? client).get<InspectPassageResponses, InspectPassageErrors, ThrowOnError>({ url: '/v1/passages/{passage_id}', ...options });

/**
 * Get Surrounding Passages
 *
 * Fetch the surrounding N passages before and after the given passage for expanded context.
 */
export const getSurroundingPassages = <ThrowOnError extends boolean = false>(options: Options<GetSurroundingPassagesData, ThrowOnError>): RequestResult<GetSurroundingPassagesResponses, GetSurroundingPassagesErrors, ThrowOnError> => (options.client ?? client).get<GetSurroundingPassagesResponses, GetSurroundingPassagesErrors, ThrowOnError>({ url: '/v1/passages/{passage_id}/surrounding', ...options });

/**
 * Retrieve
 */
export const retrieve = <ThrowOnError extends boolean = false>(options: Options<RetrieveData, ThrowOnError>): RequestResult<RetrieveResponses, RetrieveErrors, ThrowOnError> => (options.client ?? client).post<RetrieveResponses, RetrieveErrors, ThrowOnError>({
    url: '/v1/retrieve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Bulk Curation
 *
 * Apply multiple curation actions in a single batch with summary.
 */
export const bulkCuration = <ThrowOnError extends boolean = false>(options: Options<BulkCurationData, ThrowOnError>): RequestResult<BulkCurationResponses, BulkCurationErrors, ThrowOnError> => (options.client ?? client).post<BulkCurationResponses, BulkCurationErrors, ThrowOnError>({
    url: '/v1/curation/bulk',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Export Passages
 *
 * Export passages with optional filtering.
 */
export const exportPassages = <ThrowOnError extends boolean = false>(options: Options<ExportPassagesData, ThrowOnError>): RequestResult<ExportPassagesResponses, ExportPassagesErrors, ThrowOnError> => (options.client ?? client).post<ExportPassagesResponses, ExportPassagesErrors, ThrowOnError>({
    url: '/v1/curation/export',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Topics
 *
 * List all topics for a project.
 */
export const listTopics = <ThrowOnError extends boolean = false>(options: Options<ListTopicsData, ThrowOnError>): RequestResult<ListTopicsResponses, ListTopicsErrors, ThrowOnError> => (options.client ?? client).get<ListTopicsResponses, ListTopicsErrors, ThrowOnError>({ url: '/v1/projects/{project_id}/topics', ...options });

/**
 * Get Concept Graph
 *
 * Return the concept graph nodes (topics) and edges (co-occurrences).
 */
export const getConceptGraph = <ThrowOnError extends boolean = false>(options: Options<GetConceptGraphData, ThrowOnError>): RequestResult<GetConceptGraphResponses, GetConceptGraphErrors, ThrowOnError> => (options.client ?? client).get<GetConceptGraphResponses, GetConceptGraphErrors, ThrowOnError>({ url: '/v1/projects/{project_id}/concept-graph', ...options });
