// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_ingest_pdf
 */
export type BodyIngestPdf = {
    /**
     * Tenantid
     */
    tenantId: string;
    /**
     * Projectid
     */
    projectId: string;
    /**
     * Externalsourceid
     */
    externalSourceId: string;
    /**
     * Title
     */
    title: string;
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BulkCurationRequest
 */
export type BulkCurationRequest = {
    /**
     * Actions
     */
    actions: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * BulkCurationResponse
 */
export type BulkCurationResponse = {
    /**
     * Results
     */
    results: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Total
     */
    total: number;
    /**
     * Succeeded
     */
    succeeded: number;
    /**
     * Failed
     */
    failed: number;
};

/**
 * ConceptGraphResponse
 */
export type ConceptGraphResponse = {
    /**
     * Nodes
     */
    nodes: Array<TopicRecord>;
    /**
     * Edges
     */
    edges: Array<TopicEdge>;
};

/**
 * CurationStatus
 */
export type CurationStatus = 'candidate' | 'certified' | 'deprecated' | 'rejected';

/**
 * ExportPassagesRequest
 */
export type ExportPassagesRequest = {
    /**
     * Source Id
     */
    source_id?: string | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Format
     */
    format?: string;
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IngestSourceRequest
 */
export type IngestSourceRequest = {
    /**
     * Tenantid
     */
    tenantId: string;
    /**
     * Projectid
     */
    projectId: string;
    /**
     * Externalsourceid
     */
    externalSourceId: string;
    /**
     * Title
     */
    title: string;
    /**
     * Sourcetype
     */
    sourceType: 'text' | 'markdown' | 'html' | 'pdf' | 'web';
    /**
     * Text
     */
    text?: string | null;
    /**
     * Fileurl
     */
    fileUrl?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
};

/**
 * IngestSourceResponse
 */
export type IngestSourceResponse = {
    /**
     * Ingestionrunid
     */
    ingestionRunId: string;
    /**
     * Sourceid
     */
    sourceId: string;
    /**
     * Status
     */
    status: string;
    /**
     * Passagecount
     */
    passageCount: number;
    /**
     * Warningcount
     */
    warningCount: number;
};

/**
 * IngestionRunRecord
 */
export type IngestionRunRecord = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Source Id
     */
    source_id: string;
    status: IngestionStatus;
    /**
     * Failure Reason
     */
    failure_reason?: string | null;
    /**
     * Stats
     */
    stats?: {
        [key: string]: unknown;
    };
    /**
     * Started At
     */
    started_at?: unknown | null;
    /**
     * Completed At
     */
    completed_at?: unknown | null;
    /**
     * Created At
     */
    created_at?: unknown | null;
    /**
     * Updated At
     */
    updated_at?: unknown | null;
};

/**
 * IngestionStatus
 */
export type IngestionStatus = 'queued' | 'processing' | 'completed' | 'failed';

/**
 * Location
 */
export type Location = {
    /**
     * Page
     */
    page?: number | null;
    /**
     * Heading
     */
    heading?: string | null;
    /**
     * Start Offset
     */
    start_offset?: number | null;
    /**
     * End Offset
     */
    end_offset?: number | null;
};

/**
 * PaginatedPassagesResponse
 */
export type PaginatedPassagesResponse = {
    /**
     * Items
     */
    items: Array<PassageRecord>;
    /**
     * Total
     */
    total: number;
};

/**
 * PassageRecord
 */
export type PassageRecord = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Block Id
     */
    block_id: string;
    /**
     * Text
     */
    text: string;
    /**
     * Kind
     */
    kind: string;
    location: Location;
    /**
     * Order
     */
    order: number;
    /**
     * Token Count
     */
    token_count: number;
    /**
     * Quality Score
     */
    quality_score: number;
    /**
     * Quality Warnings
     */
    quality_warnings?: Array<string>;
    status?: CurationStatus;
    /**
     * Retrieval Enabled
     */
    retrieval_enabled?: boolean;
};

/**
 * RetrieveRequest
 */
export type RetrieveRequest = {
    /**
     * Tenantid
     */
    tenantId: string;
    /**
     * Projectid
     */
    projectId: string;
    /**
     * Query
     */
    query: string;
    /**
     * Topk
     */
    topK?: number;
    /**
     * Mode
     */
    mode?: 'hybrid' | 'bm25_only' | 'vector_only';
    /**
     * Filters
     */
    filters?: {
        [key: string]: unknown;
    };
};

/**
 * RetrieveResponse
 */
export type RetrieveResponse = {
    /**
     * Retrievalrunid
     */
    retrievalRunId: string;
    /**
     * Query
     */
    query: string;
    /**
     * Retrievalmode
     */
    retrievalMode: string;
    /**
     * Contexts
     */
    contexts: Array<RetrievedPassage>;
    /**
     * Debug
     */
    debug: {
        [key: string]: unknown;
    };
};

/**
 * RetrievedPassage
 */
export type RetrievedPassage = {
    /**
     * Passage Id
     */
    passage_id: string;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Text
     */
    text: string;
    /**
     * Status
     */
    status: string;
    /**
     * Quality Score
     */
    quality_score: number;
    /**
     * Token Count
     */
    token_count: number;
    /**
     * Retrieval Enabled
     */
    retrieval_enabled: boolean;
    /**
     * Score
     */
    score: number;
    /**
     * Bm25 Rank
     */
    bm25_rank?: number | null;
    /**
     * Vector Rank
     */
    vector_rank?: number | null;
    /**
     * Rrf Score
     */
    rrf_score?: number | null;
    /**
     * Final Rank
     */
    final_rank: number;
    location: Location;
};

/**
 * SourceRecord
 */
export type SourceRecord = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * External Source Id
     */
    external_source_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Source Type
     */
    source_type: 'text' | 'markdown' | 'html' | 'pdf' | 'web';
    /**
     * Metadata
     */
    metadata_?: {
        [key: string]: unknown;
    };
    status?: CurationStatus;
    /**
     * Retrieval Enabled
     */
    retrieval_enabled?: boolean;
    /**
     * Quality Warnings
     */
    quality_warnings?: Array<string>;
};

/**
 * TopicEdge
 */
export type TopicEdge = {
    /**
     * Source
     */
    source: string;
    /**
     * Target
     */
    target: string;
    /**
     * Weight
     */
    weight: number;
};

/**
 * TopicRecord
 */
export type TopicRecord = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is User Defined
     */
    is_user_defined?: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MetadataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metadata';
};

export type MetadataResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type IngestSourceData = {
    body: IngestSourceRequest;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/ingest/source';
};

export type IngestSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestSourceError = IngestSourceErrors[keyof IngestSourceErrors];

export type IngestSourceResponses = {
    /**
     * Successful Response
     */
    200: IngestSourceResponse;
};

export type IngestSourceResponse2 = IngestSourceResponses[keyof IngestSourceResponses];

export type IngestPdfData = {
    body: BodyIngestPdf;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/ingest/pdf';
};

export type IngestPdfErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestPdfError = IngestPdfErrors[keyof IngestPdfErrors];

export type IngestPdfResponses = {
    /**
     * Successful Response
     */
    200: IngestSourceResponse;
};

export type IngestPdfResponse = IngestPdfResponses[keyof IngestPdfResponses];

export type GetIngestionRunData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/v1/ingest/runs/{run_id}';
};

export type GetIngestionRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIngestionRunError = GetIngestionRunErrors[keyof GetIngestionRunErrors];

export type GetIngestionRunResponses = {
    /**
     * Successful Response
     */
    200: IngestionRunRecord;
};

export type GetIngestionRunResponse = GetIngestionRunResponses[keyof GetIngestionRunResponses];

export type ListRunsForProjectData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/ingest/projects/{project_id}/runs';
};

export type ListRunsForProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRunsForProjectError = ListRunsForProjectErrors[keyof ListRunsForProjectErrors];

export type ListRunsForProjectResponses = {
    /**
     * Response List Runs For Project
     *
     * Successful Response
     */
    200: Array<IngestionRunRecord>;
};

export type ListRunsForProjectResponse = ListRunsForProjectResponses[keyof ListRunsForProjectResponses];

export type FindStaleSourcesData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Tenant Id
         */
        tenant_id?: string;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/projects/{project_id}/sources/stale';
};

export type FindStaleSourcesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FindStaleSourcesError = FindStaleSourcesErrors[keyof FindStaleSourcesErrors];

export type FindStaleSourcesResponses = {
    /**
     * Response Find Stale Sources
     *
     * Successful Response
     */
    200: Array<SourceRecord>;
};

export type FindStaleSourcesResponse = FindStaleSourcesResponses[keyof FindStaleSourcesResponses];

export type ListSourcesData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query: {
        /**
         * Tenantid
         */
        tenantId: string;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/projects/{project_id}/sources';
};

export type ListSourcesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSourcesError = ListSourcesErrors[keyof ListSourcesErrors];

export type ListSourcesResponses = {
    /**
     * Response List Sources
     *
     * Successful Response
     */
    200: Array<SourceRecord>;
};

export type ListSourcesResponse = ListSourcesResponses[keyof ListSourcesResponses];

export type DeleteSourceWithProjectData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * External Source Id
         */
        external_source_id: string;
    };
    query: {
        /**
         * Tenantid
         */
        tenantId: string;
    };
    url: '/v1/projects/{project_id}/sources/{external_source_id}';
};

export type DeleteSourceWithProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSourceWithProjectError = DeleteSourceWithProjectErrors[keyof DeleteSourceWithProjectErrors];

export type DeleteSourceWithProjectResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSourceWithProjectData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * External Source Id
         */
        external_source_id: string;
    };
    query: {
        /**
         * Tenantid
         */
        tenantId: string;
    };
    url: '/v1/projects/{project_id}/sources/{external_source_id}';
};

export type GetSourceWithProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSourceWithProjectError = GetSourceWithProjectErrors[keyof GetSourceWithProjectErrors];

export type GetSourceWithProjectResponses = {
    /**
     * Successful Response
     */
    200: SourceRecord;
};

export type GetSourceWithProjectResponse = GetSourceWithProjectResponses[keyof GetSourceWithProjectResponses];

export type DeleteProjectData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query: {
        /**
         * Tenantid
         */
        tenantId: string;
    };
    url: '/v1/projects/{project_id}';
};

export type DeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteSourceData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * External Source Id
         */
        external_source_id: string;
    };
    query: {
        /**
         * Tenantid
         */
        tenantId: string;
    };
    url: '/v1/sources/{external_source_id}';
};

export type DeleteSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSourceError = DeleteSourceErrors[keyof DeleteSourceErrors];

export type DeleteSourceResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSourceData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * External Source Id
         */
        external_source_id: string;
    };
    query: {
        /**
         * Tenantid
         */
        tenantId: string;
    };
    url: '/v1/sources/{external_source_id}';
};

export type GetSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSourceError = GetSourceErrors[keyof GetSourceErrors];

export type GetSourceResponses = {
    /**
     * Successful Response
     */
    200: SourceRecord;
};

export type GetSourceResponse = GetSourceResponses[keyof GetSourceResponses];

export type GetSourceDownloadUrlData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * External Source Id
         */
        external_source_id: string;
    };
    query: {
        /**
         * Tenantid
         */
        tenantId: string;
    };
    url: '/v1/sources/{external_source_id}/download-url';
};

export type GetSourceDownloadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSourceDownloadUrlError = GetSourceDownloadUrlErrors[keyof GetSourceDownloadUrlErrors];

export type GetSourceDownloadUrlResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSourceViewerUrlData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * External Source Id
         */
        external_source_id: string;
    };
    query: {
        /**
         * Tenantid
         */
        tenantId: string;
    };
    url: '/v1/sources/{external_source_id}/viewer-url';
};

export type GetSourceViewerUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSourceViewerUrlError = GetSourceViewerUrlErrors[keyof GetSourceViewerUrlErrors];

export type GetSourceViewerUrlResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FindWeakPassagesData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Tenant Id
         */
        tenant_id?: string;
        /**
         * Min Quality Score
         */
        min_quality_score?: number;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/passages/weak';
};

export type FindWeakPassagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FindWeakPassagesError = FindWeakPassagesErrors[keyof FindWeakPassagesErrors];

export type FindWeakPassagesResponses = {
    /**
     * Response Find Weak Passages
     *
     * Successful Response
     */
    200: Array<PassageRecord>;
};

export type FindWeakPassagesResponse = FindWeakPassagesResponses[keyof FindWeakPassagesResponses];

export type ListPassagesData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Source Id
         */
        source_id: string;
    };
    query?: {
        /**
         * Query
         */
        query?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Retrieval Enabled
         */
        retrieval_enabled?: boolean | null;
        /**
         * Sort Field
         */
        sort_field?: string;
        /**
         * Sort Direction
         */
        sort_direction?: string;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/sources/{source_id}/passages';
};

export type ListPassagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPassagesError = ListPassagesErrors[keyof ListPassagesErrors];

export type ListPassagesResponses = {
    /**
     * Successful Response
     */
    200: PaginatedPassagesResponse;
};

export type ListPassagesResponse = ListPassagesResponses[keyof ListPassagesResponses];

export type InspectPassageData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Passage Id
         */
        passage_id: string;
    };
    query?: never;
    url: '/v1/passages/{passage_id}';
};

export type InspectPassageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InspectPassageError = InspectPassageErrors[keyof InspectPassageErrors];

export type InspectPassageResponses = {
    /**
     * Successful Response
     */
    200: PassageRecord;
};

export type InspectPassageResponse = InspectPassageResponses[keyof InspectPassageResponses];

export type GetSurroundingPassagesData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Passage Id
         */
        passage_id: string;
    };
    query?: {
        /**
         * Before
         */
        before?: number;
        /**
         * After
         */
        after?: number;
    };
    url: '/v1/passages/{passage_id}/surrounding';
};

export type GetSurroundingPassagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSurroundingPassagesError = GetSurroundingPassagesErrors[keyof GetSurroundingPassagesErrors];

export type GetSurroundingPassagesResponses = {
    /**
     * Response Get Surrounding Passages
     *
     * Successful Response
     */
    200: Array<PassageRecord>;
};

export type GetSurroundingPassagesResponse = GetSurroundingPassagesResponses[keyof GetSurroundingPassagesResponses];

export type RetrieveData = {
    body: RetrieveRequest;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/retrieve';
};

export type RetrieveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetrieveError = RetrieveErrors[keyof RetrieveErrors];

export type RetrieveResponses = {
    /**
     * Successful Response
     */
    200: RetrieveResponse;
};

export type RetrieveResponse2 = RetrieveResponses[keyof RetrieveResponses];

export type BulkCurationData = {
    body: BulkCurationRequest;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Tenant Id
         */
        tenant_id?: string;
    };
    url: '/v1/curation/bulk';
};

export type BulkCurationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkCurationError = BulkCurationErrors[keyof BulkCurationErrors];

export type BulkCurationResponses = {
    /**
     * Successful Response
     */
    200: BulkCurationResponse;
};

export type BulkCurationResponse2 = BulkCurationResponses[keyof BulkCurationResponses];

export type ExportPassagesData = {
    body: ExportPassagesRequest;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Tenant Id
         */
        tenant_id?: string;
    };
    url: '/v1/curation/export';
};

export type ExportPassagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportPassagesError = ExportPassagesErrors[keyof ExportPassagesErrors];

export type ExportPassagesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListTopicsData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query: {
        /**
         * Tenantid
         */
        tenantId: string;
    };
    url: '/v1/projects/{project_id}/topics';
};

export type ListTopicsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTopicsError = ListTopicsErrors[keyof ListTopicsErrors];

export type ListTopicsResponses = {
    /**
     * Response List Topics
     *
     * Successful Response
     */
    200: Array<TopicRecord>;
};

export type ListTopicsResponse = ListTopicsResponses[keyof ListTopicsResponses];

export type GetConceptGraphData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query: {
        /**
         * Tenantid
         */
        tenantId: string;
        /**
         * Min Weight
         *
         * Minimum edge weight (co-occurrences) to include
         */
        min_weight?: number;
    };
    url: '/v1/projects/{project_id}/concept-graph';
};

export type GetConceptGraphErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConceptGraphError = GetConceptGraphErrors[keyof GetConceptGraphErrors];

export type GetConceptGraphResponses = {
    /**
     * Successful Response
     */
    200: ConceptGraphResponse;
};

export type GetConceptGraphResponse = GetConceptGraphResponses[keyof GetConceptGraphResponses];
